// api: minimal endpoints
export function getHealth(){ return {status:"ok", ts:Date.now()}; }
export function getUsers(){ return []; } // TODO: connect to db in Week 3
// api doc line 1 - checkpoint2
// api doc line 2 - checkpoint2
// api doc line 3 - checkpoint2
// api doc line 4 - checkpoint2
// api doc line 5 - checkpoint2
// api doc line 6 - checkpoint2
// api doc line 7 - checkpoint2
// api doc line 8 - checkpoint2
// api doc line 9 - checkpoint2
// api doc line 10 - checkpoint2
// api doc line 11 - checkpoint2
// api doc line 12 - checkpoint2
// api doc line 13 - checkpoint2
// api doc line 14 - checkpoint2
// api doc line 15 - checkpoint2
// api doc line 16 - checkpoint2
// api doc line 17 - checkpoint2
// api doc line 18 - checkpoint2
// api doc line 19 - checkpoint2
// api doc line 20 - checkpoint2
// api doc line 21 - checkpoint2
// api doc line 22 - checkpoint2
// api doc line 23 - checkpoint2
// api doc line 24 - checkpoint2
// api doc line 25 - checkpoint2
// api doc line 26 - checkpoint2
// api doc line 27 - checkpoint2
// api doc line 28 - checkpoint2
// api doc line 29 - checkpoint2
// api doc line 30 - checkpoint2
// api doc line 31 - checkpoint2
// api doc line 32 - checkpoint2
// api doc line 33 - checkpoint2
// api doc line 34 - checkpoint2
// api doc line 35 - checkpoint2
// api doc line 36 - checkpoint2
// api doc line 37 - checkpoint2
// api doc line 38 - checkpoint2
// api doc line 39 - checkpoint2
// api doc line 40 - checkpoint2
// api doc line 41 - checkpoint2
// api doc line 42 - checkpoint2
// api doc line 43 - checkpoint2
// api doc line 44 - checkpoint2
// api doc line 45 - checkpoint2
// api doc line 46 - checkpoint2
// api doc line 47 - checkpoint2
// api doc line 48 - checkpoint2
// api doc line 49 - checkpoint2
// api doc line 50 - checkpoint2
// api doc line 51 - checkpoint2
// api doc line 52 - checkpoint2
// api doc line 53 - checkpoint2
// api doc line 54 - checkpoint2
// api doc line 55 - checkpoint2
// api doc line 56 - checkpoint2
// api doc line 57 - checkpoint2
// api doc line 58 - checkpoint2
// api doc line 59 - checkpoint2
// api doc line 60 - checkpoint2
