// db: in-memory stub for Week 2
export const users = [{id:1, name:"A", role:"admin"}, {id:2, name:"B", role:"staff"}];
export function listRoles(){ return Array.from(new Set(users.map(u=>u.role))); }
// TODO: replace with SQLite/ORM in Week 3
// db doc line 1 - checkpoint2
// db doc line 2 - checkpoint2
// db doc line 3 - checkpoint2
// db doc line 4 - checkpoint2
// db doc line 5 - checkpoint2
// db doc line 6 - checkpoint2
// db doc line 7 - checkpoint2
// db doc line 8 - checkpoint2
// db doc line 9 - checkpoint2
// db doc line 10 - checkpoint2
// db doc line 11 - checkpoint2
// db doc line 12 - checkpoint2
// db doc line 13 - checkpoint2
// db doc line 14 - checkpoint2
// db doc line 15 - checkpoint2
// db doc line 16 - checkpoint2
// db doc line 17 - checkpoint2
// db doc line 18 - checkpoint2
// db doc line 19 - checkpoint2
// db doc line 20 - checkpoint2
// db doc line 21 - checkpoint2
// db doc line 22 - checkpoint2
// db doc line 23 - checkpoint2
// db doc line 24 - checkpoint2
// db doc line 25 - checkpoint2
// db doc line 26 - checkpoint2
// db doc line 27 - checkpoint2
// db doc line 28 - checkpoint2
// db doc line 29 - checkpoint2
// db doc line 30 - checkpoint2
// db doc line 31 - checkpoint2
// db doc line 32 - checkpoint2
// db doc line 33 - checkpoint2
// db doc line 34 - checkpoint2
// db doc line 35 - checkpoint2
// db doc line 36 - checkpoint2
// db doc line 37 - checkpoint2
// db doc line 38 - checkpoint2
// db doc line 39 - checkpoint2
// db doc line 40 - checkpoint2
// db doc line 41 - checkpoint2
// db doc line 42 - checkpoint2
// db doc line 43 - checkpoint2
// db doc line 44 - checkpoint2
// db doc line 45 - checkpoint2
// db doc line 46 - checkpoint2
// db doc line 47 - checkpoint2
// db doc line 48 - checkpoint2
// db doc line 49 - checkpoint2
// db doc line 50 - checkpoint2
// db doc line 51 - checkpoint2
// db doc line 52 - checkpoint2
// db doc line 53 - checkpoint2
// db doc line 54 - checkpoint2
// db doc line 55 - checkpoint2
// db doc line 56 - checkpoint2
// db doc line 57 - checkpoint2
// db doc line 58 - checkpoint2
// db doc line 59 - checkpoint2
// db doc line 60 - checkpoint2
// Clarification: listRoles returns unique roles from users (demo only)
